#!/usr/bin/env python3

import sys,os,argparse,re,time,subprocess

# ==============================================================================

def error(message):
  print(message)
  sys.exit(1)

# ==============================================================================

def printversion():
  print('''
Version 0.1
  ''')
  sys.exit(0)

# ==============================================================================

def printhelp():
  print('''
NAME

  svg2pdf - convert a SVG-file to a PDF-file using Inkscape

USAGE

  $ svg2pdf INPUT.SVG [-o OUTPUT.PDF]

DESCRIPTION

  Convert a SVG-file to a PDF-file using Inkscape

OPTIONS

  -v, --verbose
    Verbose Inkscape command.

  -h, --help
    Print help.

  --version
    Print change-log.

  -o, --output STR
    Specify the output-file manually. By default it has the same name as the
    SVG-file but with the ".pdf" extension.

RELEASE

  Version 0.1, January 2016

COPYRIGHT

  T.W.J. de Geus
  tom@geus.me
  www.geus.me
  ''')

  sys.exit(0)

# ==============================================================================

# set options/arguments
opts   = [\
  ((     'input'                ),dict(nargs='+',type=str,metavar='INPUT.PDF')),
  (('-o','--output'             ),dict(nargs=1  ,type=str,metavar='STR'      )),
  (('-h','--help'               ),dict(action='store_true'                   )),
  (('-v','--verbose'            ),dict(action='store_true'                   )),
  ((     '--version'            ),dict(action='store_true'                   )),
  (('-D','--export-area-drawing'),dict(action='store_true'                   )),
]

# parse command-line arguments
# - catch help
if sys.argv[1] in ['-h','--help'   ]: printhelp()
if sys.argv[1] in [     '--version']: printversion()
# - create parser
parser = argparse.ArgumentParser(add_help=False)
for (arg,opt) in opts:
  if type(arg)==tuple: parser.add_argument(*arg,**opt)
  else               : parser.add_argument( arg,**opt)
# - execute parser / convert to "<dict>"
args = vars(parser.parse_args())
# - print help and exit
if args['help'   ]: printhelp()
if args['version']: printversion()

# check
if args['output'] is not None:
  if len(args['input'])>1:
    error('Not allowed to enter multiple input files if an output file is specified')
else:
  args['output'] = [name.replace('.svg','.pdf') for name in args['input']]

# ==============================================================================

for orig,dest in zip(args['input'],args['output']):

  if orig==dest:
    print('%s and %s are the same file'%(orig,dest))

  print('[svg2pdf] %s %s'%(orig,dest))

  orig = os.path.abspath(orig)
  dest = os.path.abspath(dest)

  if not args['verbose']:
    if args['export_area_drawing']: subprocess.check_output('inkscape --export-pdf-version="1.4" --export-area-drawing --export-pdf="{:s}" "{:s}"'.format(dest,orig),shell=True, stderr=subprocess.DEVNULL)
    else                          : subprocess.check_output('inkscape --export-pdf-version="1.4" --export-area-page    --export-pdf="{:s}" "{:s}"'.format(dest,orig),shell=True, stderr=subprocess.DEVNULL)
  else:
    if args['export_area_drawing']: print(subprocess.check_output('inkscape --export-pdf-version="1.4" --export-area-drawing --export-pdf="{:s}" "{:s}"'.format(dest,orig),shell=True))
    else                          : print(subprocess.check_output('inkscape --export-pdf-version="1.4" --export-area-page    --export-pdf="{:s}" "{:s}"'.format(dest,orig),shell=True))

